version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: gedai-rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'gedai'
      RABBITMQ_DEFAULT_PASS: 'gedai'
    ports:
      - 5672:5672
      - 15672:15672
  mongodb:
    image: gedai/mongodbrs:6
    build:
      context: ./localstack
      dockerfile: ./Dockerfile.mongodb
    container_name: gedai-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'gedai'
      MONGO_INITDB_ROOT_PASSWORD: 'gedai'
    command: 'mongod --replSet rs0 --keyFile /opt/.keyfile/keyfile --bind_ip_all'
    ports:
      - 27017:27017
  mongodb_init:
    image: mongo:6
    container_name: gedai-mongodb-init
    restart: 'no'
    depends_on: [mongodb]
    command: >-
      mongosh -u gedai -p gedai --host host.docker.internal:27017 --eval 'rs.initiate({
        "_id":"rs0",
        "members":[
          {
            "_id": 0,
            "host":"host.docker.internal:27017",
          }
        ]
      })'
  postgresdb:
    image: postgres:16
    container_name: gedai-postgresdb
    environment:
      POSTGRES_DB: gedai
      POSTGRES_USER: gedai
      POSTGRES_PASSWORD: gedai
    ports:
      - 5432:5432
