version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: gedai-rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'gedai'
      RABBITMQ_DEFAULT_PASS: 'gedai'
    ports:
      - 5672:5672
      - 15672:15672
  mongodb:
    image: mongo:6
    container_name: gedai-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'gedai'
      MONGO_INITDB_ROOT_PASSWORD: 'gedai'
    ports:
      - 27017:27017
  postgresdb:
    image: postgres:16
    container_name: gedai-postgresdb
    environment:
      POSTGRES_DB: gedai
      POSTGRES_USER: gedai
      POSTGRES_PASSWORD: gedai
    ports:
      - 5432:5432
